FROM python:3.13-slim

ENV POETRY_VERSION=2.2.1
ENV POETRY_VIRTUALENVS_CREATE=false
RUN pip install --no-cache-dir "poetry==$POETRY_VERSION"

WORKDIR /app

COPY pyproject.toml poetry.lock* ./

RUN poetry install --no-interaction --no-root --only main

COPY src ./src

ENV TEMPERATURE_SENSOR=temperature_inside \
    CRON_SCHEDULE_MINUTES=15 \
    LOG_LVL=INFO

CMD ["python", "-m", "src.services.program_operator.main"]
