FROM node:20-alpine

WORKDIR /app

COPY frontend/gewaechshaus/package*.json ./
RUN npm install

COPY frontend/gewaechshaus/ .

EXPOSE 5174

CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0", "--port", "5174"]