FROM node:20-alpine AS builder

WORKDIR /app

COPY frontend/gewaechshaus/package*.json ./

RUN npm ci

COPY frontend/gewaechshaus/ .

RUN npm run build

# Production stage
FROM nginx:alpine

COPY frontend/gewaechshaus/nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /app/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]