services:
  gewaechshaus-sensor-reader:
    build: 
      context: .
      dockerfile: Dockerfile.sensor_reader
    container_name: gewaechshaus-sensor-reader
    restart: always
    healthcheck:
      disable: true
    privileged: true
    volumes:
      - /sys/class/thermal:/sys/class/thermal:ro
    devices:
      - "/dev/gpiomem:/dev/gpiomem"
      - "/sys/bus/w1/devices:/sys/bus/w1/devices"
      - "/dev/i2c-1:/dev/i2c-1"
    env_file:
      - .env

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: gewaechshaus-api
    volumes:
      - ./data/sqlite:/data
    restart: always
    privileged: true
    devices:
      - "/dev/gpiomem:/dev/gpiomem"
    env_file:
      - .env
    ports:
      - "8002:8002"

  sqlite_web:
    image: python:3.13-slim
    container_name: sqlite-web
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ./data/sqlite:/data
    command:
      - sh
      - -c
      - |
        pip install sqlite-web && \
        python -m sqlite_web /data/greenhouse.db \
          --host=0.0.0.0 \
          --port=8080 \
          --read-only

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: gewaechshaus-frontend
    restart: always
    ports:
      - "5174:5174"
